### PR TITLE
Use consistent indentation

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by benmccann** [comment]
@scottmcculloch any thoughts about merging this PR?

**Comment by benmccann** [comment]
@scottmcculloch any reason not to merge this PR?

**Comment by scottmcculloch** [comment]
> @scottmcculloch any reason not to merge this PR?

No reason that I know of not to merge... having said that, I don't know _how_ to do that.

**Comment by benmccann** [comment]
There should be a button that says merge or squash and merge or something like that. Just press the button. Then we think it will let you edit the commit message and you need to press a button to confirm

**Comment by scottmcculloch** [comment]
Ok, thanks @benmccann -- I think it's done. :-)

**Comment by benmccann** [comment]
thanks!

**Pull request merged**
